/**
 * Seed Script: Smart Farmer Scheme Assistant
 * Seeds Government Schemes, Insurance Products, and Weather Risk data
 */

require('dotenv').config();
const { prisma } = require('./config/prisma');

const governmentSchemes = [
  // ===== PM-KISAN =====
  {
    schemeCode: "PMKISAN",
    schemeName: "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
    schemeNameHi: "प्रधानमंत्री किसान सम्मान निधि",
    schemeNameMr: "प्रधानमंत्री किसान सन्मान निधी",
    description: "Direct income support of ₹6,000 per year in three installments of ₹2,000 each to small and marginal farmer families having combined land holding up to 2 hectares.",
    descriptionHi: "छोटे और सीमांत किसान परिवारों को प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता, ₹2,000 की तीन किस्तों में।",
    descriptionMr: "लहान आणि अल्प भूधारक शेतकरी कुटुंबांना दरवर्षी ₹6,000 ची थेट उत्पन्न मदत, ₹2,000 च्या तीन हप्त्यांमध्ये.",
    category: "direct_benefit",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    benefitAmount: "₹6,000 per year (₹2,000 x 3 installments)",
    benefitType: "cash",
    eligibilityCriteria: { minLand: 0, maxLand: 5, farmerTypes: ["small", "marginal"], maxIncome: null },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: 5,
    farmerTypes: ["small", "marginal", "medium"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Land Ownership Documents", "Bank Account Details", "Mobile Number"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि स्वामित्व दस्तावेज", "बैंक खाता विवरण", "मोबाइल नंबर"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन मालकी कागदपत्रे", "बँक खाते तपशील", "मोबाइल नंबर"],
    applicationProcess: "1. Visit PM-KISAN portal or CSC center\n2. Fill registration form with Aadhaar & land details\n3. Submit bank account details\n4. Verification by state government\n5. Receive ₹2,000 every 4 months",
    applicationProcessHi: "1. PM-KISAN पोर्टल या CSC केंद्र पर जाएं\n2. आधार और भूमि विवरण के साथ पंजीकरण फॉर्म भरें\n3. बैंक खाता विवरण जमा करें\n4. राज्य सरकार द्वारा सत्यापन\n5. हर 4 महीने में ₹2,000 प्राप्त करें",
    applicationProcessMr: "1. PM-KISAN पोर्टल किंवा CSC केंद्रावर जा\n2. आधार आणि जमीन तपशीलासह नोंदणी फॉर्म भरा\n3. बँक खाते तपशील सादर करा\n4. राज्य सरकारकडून पडताळणी\n5. दर 4 महिन्यांनी ₹2,000 मिळवा",
    websiteUrl: "https://pmkisan.gov.in",
    helplineNumber: "155261",
    status: "Active",
    priority: 10
  },
  // ===== PMFBY =====
  {
    schemeCode: "PMFBY",
    schemeName: "PMFBY (Pradhan Mantri Fasal Bima Yojana)",
    schemeNameHi: "प्रधानमंत्री फसल बीमा योजना",
    schemeNameMr: "प्रधानमंत्री पीक विमा योजना",
    description: "Crop insurance scheme providing financial support to farmers suffering crop loss due to natural calamities, pests & diseases. Premium: Kharif-2%, Rabi-1.5%, Commercial-5%.",
    descriptionHi: "प्राकृतिक आपदाओं, कीटों और बीमारियों से फसल नुकसान झेलने वाले किसानों को वित्तीय सहायता प्रदान करने वाली फसल बीमा योजना।",
    descriptionMr: "नैसर्गिक आपत्ती, कीटक आणि रोगांमुळे पीक नुकसान सहन करणाऱ्या शेतकऱ्यांना आर्थिक सहाय्य देणारी पीक विमा योजना.",
    category: "insurance",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    benefitAmount: "Up to full sum insured based on crop loss assessment",
    benefitType: "insurance_coverage",
    eligibilityCriteria: { minLand: 0, maxLand: null, crops: ["all"], farmerTypes: ["all"] },
    cropTypes: ["Rice", "Wheat", "Cotton", "Soybean", "Sugarcane", "Jowar", "Bajra", "Maize", "Groundnut", "Tur", "Gram", "Onion"],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: ["Kharif", "Rabi"],
    documentsRequired: ["Aadhaar Card", "Land Records (7/12 Extract)", "Sowing Certificate", "Bank Account Details", "Crop Details"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि अभिलेख (7/12)", "बुवाई प्रमाणपत्र", "बैंक खाता विवरण", "फसल विवरण"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन अभिलेख (7/12 उतारा)", "पेरणी प्रमाणपत्र", "बँक खाते तपशील", "पीक तपशील"],
    applicationProcess: "1. Visit bank/CSC/insurance company\n2. Fill crop insurance form\n3. Submit land records and crop details\n4. Pay premium (Kharif 2%, Rabi 1.5%)\n5. Get policy document\n6. Report crop loss within 72 hours",
    applicationProcessHi: "1. बैंक/CSC/बीमा कंपनी पर जाएं\n2. फसल बीमा फॉर्म भरें\n3. भूमि अभिलेख और फसल विवरण जमा करें\n4. प्रीमियम भुगतान करें\n5. पॉलिसी दस्तावेज प्राप्त करें",
    applicationProcessMr: "1. बँक/CSC/विमा कंपनीला भेट द्या\n2. पीक विमा फॉर्म भरा\n3. जमीन अभिलेख आणि पीक तपशील सादर करा\n4. प्रीमियम भरा\n5. पॉलिसी दस्तऐवज मिळवा",
    websiteUrl: "https://pmfby.gov.in",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 9
  },
  // ===== KCC =====
  {
    schemeCode: "KCC",
    schemeName: "Kisan Credit Card (KCC)",
    schemeNameHi: "किसान क्रेडिट कार्ड",
    schemeNameMr: "किसान क्रेडिट कार्ड",
    description: "Credit facility for farmers to meet their agricultural and allied activities needs. Interest rate of 4% with timely repayment. Loan up to ₹3 lakh with interest subvention.",
    descriptionHi: "किसानों को उनकी कृषि गतिविधियों की जरूरतों को पूरा करने के लिए ऋण सुविधा। समय पर भुगतान पर 4% ब्याज दर।",
    descriptionMr: "शेतकऱ्यांना त्यांच्या कृषी कार्यांच्या गरजा भागवण्यासाठी पत सुविधा. वेळेवर परतफेडीवर 4% व्याजदर.",
    category: "loan",
    ministry: "Ministry of Finance / NABARD",
    benefitAmount: "Up to ₹3,00,000 at 4% interest (with subvention)",
    benefitType: "loan_waiver",
    eligibilityCriteria: { minLand: 0, maxLand: null, farmerTypes: ["all"] },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Land Documents (7/12 Extract)", "Passport Size Photos", "Bank Account", "Income Certificate"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि दस्तावेज (7/12)", "पासपोर्ट साइज फोटो", "बैंक खाता", "आय प्रमाणपत्र"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन कागदपत्रे (7/12 उतारा)", "पासपोर्ट साइज फोटो", "बँक खाते", "उत्पन्न प्रमाणपत्र"],
    applicationProcess: "1. Visit nearest bank branch\n2. Ask for KCC application form\n3. Submit land documents\n4. Bank verifies documents\n5. KCC issued within 14 days\n6. Withdraw money as needed",
    applicationProcessHi: "1. निकटतम बैंक शाखा पर जाएं\n2. KCC आवेदन फॉर्म मांगें\n3. भूमि दस्तावेज जमा करें\n4. बैंक दस्तावेजों का सत्यापन करता है\n5. 14 दिन में KCC जारी",
    applicationProcessMr: "1. जवळच्या बँक शाखेला भेट द्या\n2. KCC अर्ज फॉर्म मागा\n3. जमीन कागदपत्रे सादर करा\n4. बँक कागदपत्रांची पडताळणी करते\n5. 14 दिवसांत KCC जारी",
    websiteUrl: "https://www.nabard.org",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 8
  },
  // ===== PM Krishi Sinchai Yojana =====
  {
    schemeCode: "PMKSY",
    schemeName: "PM Krishi Sinchai Yojana (PMKSY)",
    schemeNameHi: "प्रधानमंत्री कृषि सिंचाई योजना",
    schemeNameMr: "प्रधानमंत्री कृषी सिंचन योजना",
    description: "Provides subsidies for micro-irrigation (drip and sprinkler systems). Up to 55% subsidy for small/marginal farmers and 45% for others.",
    descriptionHi: "सूक्ष्म सिंचाई (ड्रिप और स्प्रिंकलर) के लिए सब्सिडी। छोटे/सीमांत किसानों के लिए 55% तक सब्सिडी।",
    descriptionMr: "सूक्ष्म सिंचन (ठिबक आणि तुषार) साठी अनुदान. लहान/अल्पभूधारक शेतकऱ्यांना 55% पर्यंत अनुदान.",
    category: "subsidy",
    ministry: "Ministry of Agriculture",
    benefitAmount: "55% subsidy for small farmers, 45% for others",
    benefitType: "subsidy",
    eligibilityCriteria: { minLand: 0, maxLand: null, farmerTypes: ["all"] },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Land Documents", "Bank Account", "Quotation from irrigation equipment supplier", "Caste Certificate (if applicable)"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि दस्तावेज", "बैंक खाता", "सिंचाई उपकरण आपूर्तिकर्ता का कोटेशन", "जाति प्रमाणपत्र"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन कागदपत्रे", "बँक खाते", "सिंचन उपकरण पुरवठादाराचे कोटेशन", "जात प्रमाणपत्र"],
    applicationProcess: "1. Apply online through state agriculture portal\n2. Submit required documents\n3. Get technical verification visit\n4. Install irrigation system\n5. Submit bills for reimbursement\n6. Receive subsidy in bank account",
    websiteUrl: "https://pmksy.gov.in",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 7
  },
  // ===== Soil Health Card =====
  {
    schemeCode: "SHC",
    schemeName: "Soil Health Card Scheme",
    schemeNameHi: "मृदा स्वास्थ्य कार्ड योजना",
    schemeNameMr: "मृदा आरोग्य कार्ड योजना",
    description: "Free soil testing and health card for farmers with crop-wise fertilizer recommendations. Issued every 2 years.",
    descriptionHi: "किसानों के लिए मुफ्त मिट्टी परीक्षण और स्वास्थ्य कार्ड। फसलवार उर्वरक सिफारिशें।",
    descriptionMr: "शेतकऱ्यांसाठी मोफत माती परीक्षण आणि आरोग्य कार्ड. पीकनिहाय खत शिफारसी.",
    category: "direct_benefit",
    ministry: "Ministry of Agriculture",
    benefitAmount: "Free soil testing service",
    benefitType: "subsidy",
    eligibilityCriteria: { minLand: 0, maxLand: null, farmerTypes: ["all"] },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Land Details"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि विवरण"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन तपशील"],
    applicationProcess: "1. Visit nearest Krishi Vigyan Kendra or agriculture office\n2. Give soil sample\n3. Receive soil health card within 15 days\n4. Follow recommendations for fertilizer use",
    websiteUrl: "https://soilhealth.dac.gov.in",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 6
  },
  // ===== Maharashtra: Mahatma Jyotirao Phule Shetkari Karj Mukti =====
  {
    schemeCode: "MJPSKM",
    schemeName: "Mahatma Jyotirao Phule Shetkari Karj Mukti Yojana",
    schemeNameHi: "महात्मा ज्योतिराव फुले शेतकरी कर्ज माफी योजना",
    schemeNameMr: "महात्मा ज्योतिराव फुले शेतकरी कर्ज मुक्ती योजना",
    description: "Farm loan waiver scheme for Maharashtra farmers. Waives outstanding crop loans up to ₹2 lakh taken from banks.",
    descriptionHi: "महाराष्ट्र किसानों के लिए कृषि ऋण माफी योजना। बैंकों से लिए गए ₹2 लाख तक के बकाया फसल ऋण माफ।",
    descriptionMr: "महाराष्ट्र शेतकऱ्यांसाठी कृषी कर्ज माफी योजना. बँकांकडून घेतलेले ₹2 लाखांपर्यंतचे थकित पीक कर्ज माफ.",
    category: "loan",
    ministry: "Maharashtra State Government",
    benefitAmount: "Loan waiver up to ₹2,00,000",
    benefitType: "loan_waiver",
    eligibilityCriteria: { minLand: 0, maxLand: 5, states: ["Maharashtra"], farmerTypes: ["small", "marginal"] },
    cropTypes: [],
    applicableStates: ["Maharashtra"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: 5,
    farmerTypes: ["small", "marginal"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "7/12 Extract", "8-A Extract", "Bank Loan Details", "Ration Card"],
    documentsRequiredHi: ["आधार कार्ड", "7/12 उतारा", "8-A उतारा", "बैंक ऋण विवरण", "राशन कार्ड"],
    documentsRequiredMr: ["आधार कार्ड", "7/12 उतारा", "8-अ उतारा", "बँक कर्ज तपशील", "रेशन कार्ड"],
    applicationProcess: "1. Visit https://mjpsky.maharashtra.gov.in\n2. Enter Aadhaar number\n3. Verify bank loan details\n4. Submit application\n5. State government processes waiver\n6. Loan amount adjusted in bank account",
    websiteUrl: "https://mjpsky.maharashtra.gov.in",
    helplineNumber: "1800-120-8040",
    status: "Active",
    priority: 8,
  },
  // ===== Namo Shetkari Mahasanman Nidhi =====
  {
    schemeCode: "NSMN",
    schemeName: "Namo Shetkari Mahasanman Nidhi Yojana",
    schemeNameHi: "नमो शेतकरी महासन्मान निधि योजना",
    schemeNameMr: "नमो शेतकरी महासन्मान निधी योजना",
    description: "Maharashtra state scheme providing ₹6,000 per year to farmers in addition to PM-KISAN. Total benefit: ₹12,000/year (₹6,000 PM-KISAN + ₹6,000 State).",
    descriptionHi: "PM-KISAN के अतिरिक्त किसानों को प्रति वर्ष ₹6,000 प्रदान करने वाली महाराष्ट्र राज्य योजना।",
    descriptionMr: "PM-KISAN व्यतिरिक्त शेतकऱ्यांना दरवर्षी ₹6,000 देणारी महाराष्ट्र राज्य योजना.",
    category: "direct_benefit",
    ministry: "Maharashtra State Government",
    benefitAmount: "₹6,000 per year (additional to PM-KISAN)",
    benefitType: "cash",
    eligibilityCriteria: { minLand: 0, maxLand: null, states: ["Maharashtra"], farmerTypes: ["all"] },
    cropTypes: [],
    applicableStates: ["Maharashtra"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "7/12 Extract", "8-A Extract", "Bank Account Details", "PM-KISAN Registration"],
    documentsRequiredHi: ["आधार कार्ड", "7/12 उतारा", "8-अ उतारा", "बैंक खाता विवरण", "PM-KISAN पंजीकरण"],
    documentsRequiredMr: ["आधार कार्ड", "7/12 उतारा", "8-अ उतारा", "बँक खाते तपशील", "PM-KISAN नोंदणी"],
    applicationProcess: "1. Must be registered under PM-KISAN\n2. State automatically identifies eligible farmers\n3. ₹2,000 transferred every 4 months\n4. Check status on MahaDBT portal",
    websiteUrl: "https://mahadbt.maharashtra.gov.in",
    helplineNumber: "1800-120-8040",
    status: "Active",
    priority: 9,
  },
  // ===== e-NAM =====
  {
    schemeCode: "ENAM",
    schemeName: "e-NAM (National Agriculture Market)",
    schemeNameHi: "ई-नाम (राष्ट्रीय कृषि बाजार)",
    schemeNameMr: "ई-नाम (राष्ट्रीय कृषी बाजार)",
    description: "Online trading platform for agricultural produce. Farmers can sell crops at best market price through transparent bidding across mandis.",
    descriptionHi: "कृषि उपज के लिए ऑनलाइन ट्रेडिंग प्लेटफॉर्म। किसान पारदर्शी बोली के माध्यम से सर्वोत्तम बाजार मूल्य पर फसल बेच सकते हैं।",
    descriptionMr: "कृषी उत्पादनासाठी ऑनलाइन व्यापार मंच. शेतकरी पारदर्शी बोलीद्वारे सर्वोत्तम बाजारभावाने पीक विकू शकतात.",
    category: "direct_benefit",
    ministry: "Ministry of Agriculture",
    benefitAmount: "Better market prices through transparent bidding",
    benefitType: "cash",
    eligibilityCriteria: { minLand: 0, maxLand: null, farmerTypes: ["all"] },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Bank Account", "Mobile Number", "Land Document (optional)"],
    documentsRequiredHi: ["आधार कार्ड", "बैंक खाता", "मोबाइल नंबर", "भूमि दस्तावेज (वैकल्पिक)"],
    documentsRequiredMr: ["आधार कार्ड", "बँक खाते", "मोबाइल नंबर", "जमीन कागदपत्र (ऐच्छिक)"],
    applicationProcess: "1. Register on eNAM portal or app\n2. Link Aadhaar and bank account\n3. List your crop with quantity and quality\n4. Traders bid online\n5. Accept best price\n6. Payment directly to bank",
    websiteUrl: "https://enam.gov.in",
    helplineNumber: "1800-270-0224",
    status: "Active",
    priority: 5,
  },
  // ===== PKVY (Organic Farming) =====
  {
    schemeCode: "PKVY",
    schemeName: "Paramparagat Krishi Vikas Yojana (PKVY)",
    schemeNameHi: "परम्परागत कृषि विकास योजना",
    schemeNameMr: "परंपरागत कृषी विकास योजना",
    description: "Promotes organic farming. ₹50,000 per hectare for 3 years for organic farming inputs, certification and marketing.",
    descriptionHi: "जैविक खेती को बढ़ावा देता है। 3 वर्षों के लिए प्रति हेक्टेयर ₹50,000।",
    descriptionMr: "सेंद्रिय शेतीला प्रोत्साहन. 3 वर्षांसाठी प्रति हेक्टेयर ₹50,000.",
    category: "subsidy",
    ministry: "Ministry of Agriculture",
    benefitAmount: "₹50,000 per hectare for 3 years",
    benefitType: "subsidy",
    eligibilityCriteria: { minLand: 0.5, maxLand: null, farmerTypes: ["all"] },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0.5,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Land Documents", "Group Certificate (20+ farmers)", "Bank Account"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि दस्तावेज", "समूह प्रमाणपत्र (20+ किसान)", "बैंक खाता"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन कागदपत्रे", "गट प्रमाणपत्र (20+ शेतकरी)", "बँक खाते"],
    applicationProcess: "1. Form a group of minimum 20 farmers\n2. Register with District Agriculture Officer\n3. Get organic certification\n4. Follow organic farming practices\n5. Receive subsidy in installments",
    websiteUrl: "https://pgsindia-ncof.gov.in",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 5,
  },
  // ===== PMKMY (Pension) =====
  {
    schemeCode: "PMKMY",
    schemeName: "PM Kisan Maandhan Yojana (Pension)",
    schemeNameHi: "प्रधानमंत्री किसान मानधन योजना",
    schemeNameMr: "प्रधानमंत्री किसान मानधन योजना",
    description: "Pension scheme for small and marginal farmers. ₹3,000 monthly pension after age 60. Monthly contribution ₹55-200 based on entry age.",
    descriptionHi: "छोटे और सीमांत किसानों के लिए पेंशन योजना। 60 वर्ष बाद ₹3,000 मासिक पेंशन।",
    descriptionMr: "लहान आणि अल्पभूधारक शेतकऱ्यांसाठी पेंशन योजना. 60 वर्षांनंतर ₹3,000 मासिक पेंशन.",
    category: "pension",
    ministry: "Ministry of Agriculture",
    benefitAmount: "₹3,000 per month pension after 60 years",
    benefitType: "cash",
    eligibilityCriteria: { minLand: 0, maxLand: 2, farmerTypes: ["small", "marginal"], maxAge: 40, minAge: 18 },
    cropTypes: [],
    applicableStates: ["All States"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: 2,
    farmerTypes: ["small", "marginal"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Bank Account", "Land Documents", "Age Proof"],
    documentsRequiredHi: ["आधार कार्ड", "बैंक खाता", "भूमि दस्तावेज", "आयु प्रमाण"],
    documentsRequiredMr: ["आधार कार्ड", "बँक खाते", "जमीन कागदपत्रे", "वय प्रमाण"],
    applicationProcess: "1. Visit CSC center\n2. Self-register on PM-KMY portal\n3. Submit Aadhaar and bank details\n4. Monthly contribution auto-debited\n5. ₹3,000/month pension from age 60",
    websiteUrl: "https://pmkmy.gov.in",
    helplineNumber: "1800-267-6888",
    status: "Active",
    priority: 7,
  },
  // ===== Cotton/Soybean Crop Specific =====
  {
    schemeCode: "CCIS",
    schemeName: "Cotton & Soybean Crop Insurance Special",
    schemeNameHi: "कपास एवं सोयाबीन फसल बीमा विशेष",
    schemeNameMr: "कापूस आणि सोयाबीन पीक विमा विशेष",
    description: "Special crop insurance for cotton and soybean farmers in Maharashtra. Enhanced coverage and lower premium rates.",
    descriptionHi: "महाराष्ट्र में कपास और सोयाबीन किसानों के लिए विशेष फसल बीमा।",
    descriptionMr: "महाराष्ट्रातील कापूस आणि सोयाबीन शेतकऱ्यांसाठी विशेष पीक विमा.",
    category: "insurance",
    ministry: "Maharashtra State Government",
    benefitAmount: "Sum insured up to ₹40,000/hectare",
    benefitType: "insurance_coverage",
    eligibilityCriteria: { minLand: 0, maxLand: null, crops: ["Cotton", "Soybean"], states: ["Maharashtra"] },
    cropTypes: ["Cotton", "Soybean"],
    applicableStates: ["Maharashtra"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: ["Kharif"],
    documentsRequired: ["Aadhaar Card", "7/12 Extract", "Sowing Certificate", "Bank Account", "Previous Season Crop Record"],
    documentsRequiredHi: ["आधार कार्ड", "7/12 उतारा", "बुवाई प्रमाणपत्र", "बैंक खाता", "पिछले सीजन का फसल रिकॉर्ड"],
    documentsRequiredMr: ["आधार कार्ड", "7/12 उतारा", "पेरणी प्रमाणपत्र", "बँक खाते", "मागील हंगामाचा पीक अहवाल"],
    applicationProcess: "1. Apply before sowing deadline at bank\n2. Submit crop and land details\n3. Pay subsidized premium\n4. Report damage within 72 hrs if crop loss occurs",
    websiteUrl: "https://pmfby.gov.in",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 8,
  },
  // ===== Sugarcane Development =====
  {
    schemeCode: "SCDEV",
    schemeName: "Sugarcane Development & Price Support",
    schemeNameHi: "गन्ना विकास एवं मूल्य समर्थन",
    schemeNameMr: "ऊस विकास आणि किंमत आधार",
    description: "Fair and Remunerative Price (FRP) support for sugarcane farmers. Minimum price guarantee and development subsidy.",
    descriptionHi: "गन्ना किसानों के लिए उचित और लाभकारी मूल्य (FRP) समर्थन।",
    descriptionMr: "ऊस शेतकऱ्यांसाठी वाजवी आणि फायदेशीर किंमत (FRP) आधार.",
    category: "subsidy",
    ministry: "Ministry of Agriculture",
    benefitAmount: "FRP ₹315/quintal + State Advisory Price",
    benefitType: "cash",
    eligibilityCriteria: { minLand: 0, maxLand: null, crops: ["Sugarcane"] },
    cropTypes: ["Sugarcane"],
    applicableStates: ["Maharashtra", "Uttar Pradesh", "Karnataka"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "Land Documents", "Sugar Factory Slip", "Bank Account"],
    documentsRequiredHi: ["आधार कार्ड", "भूमि दस्तावेज", "चीनी मिल पर्ची", "बैंक खाता"],
    documentsRequiredMr: ["आधार कार्ड", "जमीन कागदपत्रे", "साखर कारखाना स्लिप", "बँक खाते"],
    applicationProcess: "1. Register with local sugar factory\n2. Supply sugarcane to factory\n3. Factory pays FRP within 14 days\n4. State advisory price paid additionally",
    websiteUrl: "https://dfpd.gov.in",
    helplineNumber: "1800-180-1551",
    status: "Active",
    priority: 6,
  },
  // ===== Onion Storage Subsidy =====
  {
    schemeCode: "ONIONSUB",
    schemeName: "Onion Storage Structure Subsidy",
    schemeNameHi: "प्याज भंडारण संरचना सब्सिडी",
    schemeNameMr: "कांदा साठवणूक संरचना अनुदान",
    description: "50% subsidy (up to ₹87,500) for construction of onion storage structures to reduce post-harvest losses in Maharashtra.",
    descriptionHi: "महाराष्ट्र में प्याज भंडारण संरचनाओं के निर्माण पर 50% सब्सिडी (₹87,500 तक)।",
    descriptionMr: "महाराष्ट्रात कांदा साठवणूक संरचनांच्या बांधकामावर 50% अनुदान (₹87,500 पर्यंत).",
    category: "subsidy",
    ministry: "Maharashtra State Government",
    benefitAmount: "50% subsidy up to ₹87,500",
    benefitType: "subsidy",
    eligibilityCriteria: { minLand: 0, maxLand: null, crops: ["Onion"], states: ["Maharashtra"] },
    cropTypes: ["Onion"],
    applicableStates: ["Maharashtra"],
    applicableDistricts: [],
    minLandSize: 0,
    maxLandSize: null,
    farmerTypes: ["small", "marginal", "medium", "large"],
    farmerCategories: ["SC", "ST", "OBC", "General"],
    season: [],
    documentsRequired: ["Aadhaar Card", "7/12 Extract", "Land Ownership Proof", "Construction Estimate", "Bank Account"],
    documentsRequiredHi: ["आधार कार्ड", "7/12 उतारा", "भूमि स्वामित्व प्रमाण", "निर्माण अनुमान", "बैंक खाता"],
    documentsRequiredMr: ["आधार कार्ड", "7/12 उतारा", "जमीन मालकी पुरावा", "बांधकाम अंदाजपत्रक", "बँक खाते"],
    applicationProcess: "1. Apply at District Agriculture Office\n2. Submit construction plan\n3. Get approval\n4. Build storage structure\n5. Submit completion certificate\n6. Receive 50% subsidy",
    websiteUrl: "https://mahadbt.maharashtra.gov.in",
    helplineNumber: "1800-120-8040",
    status: "Active",
    priority: 6,
  }
];

const insuranceProducts = [
  {
    productCode: "PMFBY_KHARIF",
    productName: "PMFBY - Kharif Season",
    productNameHi: "PMFBY - खरीफ सीजन",
    productNameMr: "PMFBY - खरीप हंगाम",
    description: "Crop insurance for Kharif season crops. Premium rate: 2% of sum insured. Government pays remaining premium.",
    descriptionHi: "खरीफ मौसम की फसलों के लिए फसल बीमा। प्रीमियम दर: बीमित राशि का 2%।",
    descriptionMr: "खरीप हंगामातील पिकांसाठी पीक विमा. प्रीमियम दर: विमा रकमेच्या 2%.",
    insuranceType: "crop",
    provider: "Agriculture Insurance Company of India",
    premiumRate: 2.0,
    sumInsured: 50000,
    coverageDetails: "Covers: Pre-sowing to post-harvest losses including prevented sowing, standing crop, localized calamities, post-harvest losses, and wild animal attacks.",
    coverageDetailsHi: "कवर: बुवाई पूर्व से कटाई के बाद तक के नुकसान।",
    coverageDetailsMr: "कव्हर: पेरणीपूर्व ते कापणीनंतरच्या नुकसानापर्यंत.",
    applicableCrops: ["Rice", "Soybean", "Cotton", "Maize", "Bajra", "Jowar", "Groundnut", "Tur"],
    applicableStates: ["All States"],
    season: ["Kharif"],
    subsidyPercentage: 95,
    claimProcess: "1. Report crop loss within 72 hours via app/helpline\n2. Insurance company surveys damage\n3. Yield data compared with threshold\n4. Claim settled within 2 months",
    claimProcessHi: "1. 72 घंटे के भीतर फसल नुकसान की रिपोर्ट करें\n2. बीमा कंपनी नुकसान का सर्वे करती है\n3. दावा 2 महीने में निपटाया जाता है",
    claimProcessMr: "1. 72 तासांच्या आत पीक नुकसानाची माहिती द्या\n2. विमा कंपनी नुकसानीचे सर्वेक्षण करते\n3. दावा 2 महिन्यांत निकाली काढला जातो",
    documentsRequired: ["Aadhaar Card", "7/12 Extract", "Sowing Certificate", "Bank Passbook", "Crop Loss Photos"],
    status: "Active",
    riskLevel: "medium"
  },
  {
    productCode: "PMFBY_RABI",
    productName: "PMFBY - Rabi Season",
    productNameHi: "PMFBY - रबी सीजन",
    productNameMr: "PMFBY - रब्बी हंगाम",
    description: "Crop insurance for Rabi season crops. Premium rate: 1.5% of sum insured. Government pays remaining premium.",
    descriptionHi: "रबी मौसम की फसलों के लिए फसल बीमा। प्रीमियम दर: बीमित राशि का 1.5%।",
    descriptionMr: "रब्बी हंगामातील पिकांसाठी पीक विमा. प्रीमियम दर: विमा रकमेच्या 1.5%.",
    insuranceType: "crop",
    provider: "Agriculture Insurance Company of India",
    premiumRate: 1.5,
    sumInsured: 50000,
    coverageDetails: "Covers Rabi season crop losses including Wheat, Gram, Jowar (Rabi), Onion. Same coverage as Kharif.",
    applicableCrops: ["Wheat", "Gram", "Jowar", "Onion", "Maize"],
    applicableStates: ["All States"],
    season: ["Rabi"],
    subsidyPercentage: 95,
    claimProcess: "Same as PMFBY Kharif - Report within 72 hours",
    documentsRequired: ["Aadhaar Card", "7/12 Extract", "Sowing Certificate", "Bank Passbook"],
    status: "Active",
    riskLevel: "medium"
  },
  {
    productCode: "RWBCIS",
    productName: "RWBCIS (Weather Based Crop Insurance)",
    productNameHi: "RWBCIS (मौसम आधारित फसल बीमा)",
    productNameMr: "RWBCIS (हवामान आधारित पीक विमा)",
    description: "Weather-based crop insurance using weather parameters like rainfall, temperature, humidity. Automatic payout on adverse weather.",
    descriptionHi: "वर्षा, तापमान, आर्द्रता जैसे मौसम मापदंडों का उपयोग करके मौसम आधारित फसल बीमा।",
    descriptionMr: "पाऊस, तापमान, आर्द्रता यांसारख्या हवामान मापदंडांचा वापर करून हवामान आधारित पीक विमा.",
    insuranceType: "weather",
    provider: "ICICI Lombard / HDFC ERGO",
    premiumRate: 5.0,
    sumInsured: 40000,
    coverageDetails: "Automatic payout when rainfall deficit > 20%, excess rainfall > 150% of normal, temperature extremes, or hailstorm events occur.",
    applicableCrops: ["All Crops"],
    applicableStates: ["All States"],
    season: ["Kharif", "Rabi"],
    subsidyPercentage: 50,
    claimProcess: "1. Automatic trigger based on weather station data\n2. No need to report crop loss\n3. Payment auto-credited to bank account\n4. Settlement faster than traditional insurance",
    documentsRequired: ["Aadhaar Card", "Land Documents", "Bank Account", "Crop Details"],
    status: "Active",
    riskLevel: "low"
  },
  {
    productCode: "LIVESTOCK_INS",
    productName: "Livestock Insurance Scheme",
    productNameHi: "पशुधन बीमा योजना",
    productNameMr: "पशुधन विमा योजना",
    description: "Insurance coverage for cattle, buffalo, sheep, goat. Premium subsidy of 50% for general and 70% for SC/ST farmers.",
    descriptionHi: "पशु, भैंस, भेड़, बकरी के लिए बीमा कवर। प्रीमियम सब्सिडी 50-70%।",
    descriptionMr: "गाय, म्हैस, मेंढी, शेळी यांसाठी विमा कव्हर. प्रीमियम अनुदान 50-70%.",
    insuranceType: "livestock",
    provider: "Various Insurance Companies",
    premiumRate: 3.0,
    sumInsured: 100000,
    coverageDetails: "Covers death of livestock due to disease, accident, natural calamity. Market value reimbursement.",
    applicableCrops: [],
    applicableStates: ["All States"],
    season: [],
    subsidyPercentage: 50,
    claimProcess: "1. Report death within 24 hours\n2. Veterinary post-mortem required\n3. Submit ear tag and photos\n4. Claim processed within 15 days",
    documentsRequired: ["Aadhaar Card", "Ear Tag Certificate", "Veterinary Health Certificate", "Bank Account"],
    status: "Active",
    riskLevel: "medium"
  }
];

async function seedData() {
  try {
    console.log('🌱 Starting seed process...\n');

    // Clear existing data
    console.log('🗑️  Clearing existing data...');
    await prisma.schemeReminder.deleteMany({});
    await prisma.weatherRiskAlert.deleteMany({});
    await prisma.schemeApplication.deleteMany({});
    await prisma.insuranceProduct.deleteMany({});
    await prisma.governmentScheme.deleteMany({});
    
    // Seed Government Schemes
    console.log('📋 Seeding Government Schemes...');
    for (const scheme of governmentSchemes) {
      await prisma.governmentScheme.create({ data: scheme });
      console.log(`   ✅ ${scheme.schemeName}`);
    }

    // Seed Insurance Products
    console.log('\n🛡️  Seeding Insurance Products...');
    for (const product of insuranceProducts) {
      await prisma.insuranceProduct.create({ data: product });
      console.log(`   ✅ ${product.productName}`);
    }

    // Seed Weather Risk Alerts
    console.log('\n⛈️  Seeding Weather Risk Alerts...');
    const weatherAlerts = [
      {
        district: "Nashik",
        riskType: "hailstorm",
        riskLevel: "high",
        description: "High probability of hailstorm in Nashik district. Grape and onion crops at risk.",
        descriptionHi: "नासिक जिले में ओलावृष्टि की अधिक संभावना। अंगूर और प्याज की फसल खतरे में।",
        descriptionMr: "नाशिक जिल्ह्यात गारपिटीची अधिक शक्यता. द्राक्षे आणि कांदा पिके धोक्यात.",
        affectedCrops: ["Grapes", "Onion"],
        recommendedActions: ["Cover crops with protective nets", "Harvest mature crops early", "Apply for crop insurance before deadline"],
        recommendedActionsHi: ["फसलों को सुरक्षात्मक जालों से ढकें", "पकी फसल जल्दी काटें", "समय सीमा से पहले फसल बीमा के लिए आवेदन करें"],
        recommendedActionsMr: ["पिकांना संरक्षक जाळ्यांनी झाका", "पिकलेली पिके लवकर काढा", "मुदतीपूर्वी पीक विमासाठी अर्ज करा"],
        insuranceSuggestion: "PMFBY_RABI",
        isActive: true
      },
      {
        district: "Pune",
        riskType: "drought",
        riskLevel: "medium",
        description: "Below normal rainfall expected. Drought-like conditions possible in eastern Pune.",
        descriptionHi: "सामान्य से कम वर्षा की उम्मीद। पूर्वी पुणे में सूखे जैसी स्थिति संभव।",
        descriptionMr: "सामान्यपेक्षा कमी पावसाची अपेक्षा. पूर्व पुणे भागात दुष्काळसदृश परिस्थिती शक्य.",
        affectedCrops: ["Sugarcane", "Soybean", "Jowar"],
        recommendedActions: ["Use drip irrigation", "Apply mulching", "Plant drought-resistant varieties", "Apply for weather-based insurance"],
        recommendedActionsHi: ["ड्रिप सिंचाई का उपयोग करें", "मल्चिंग लगाएं", "सूखा प्रतिरोधी किस्में लगाएं"],
        recommendedActionsMr: ["ठिबक सिंचन वापरा", "आच्छादन करा", "दुष्काळ प्रतिरोधक वाण लावा"],
        insuranceSuggestion: "RWBCIS",
        isActive: true
      },
      {
        district: "Nagpur",
        riskType: "pest",
        riskLevel: "medium",
        description: "Pink bollworm alert for cotton growing areas in Vidarbha region.",
        descriptionHi: "विदर्भ क्षेत्र में कपास उगाने वाले क्षेत्रों में गुलाबी बॉलवर्म की चेतावनी।",
        descriptionMr: "विदर्भ विभागातील कापूस पिकवणाऱ्या भागात गुलाबी बोंडअळीची सूचना.",
        affectedCrops: ["Cotton"],
        recommendedActions: ["Use pheromone traps", "Apply recommended pesticides", "Ensure crop insurance", "Destroy crop residues after harvest"],
        recommendedActionsHi: ["फेरोमोन ट्रैप का उपयोग करें", "अनुशंसित कीटनाशकों का प्रयोग करें"],
        recommendedActionsMr: ["फेरोमोन सापळे वापरा", "शिफारशीनुसार कीटकनाशकांचा वापर करा"],
        insuranceSuggestion: "PMFBY_KHARIF",
        isActive: true
      },
      {
        district: "Aurangabad",
        riskType: "drought",
        riskLevel: "high",
        description: "Severe drought conditions in Marathwada region. Water crisis for crops.",
        descriptionHi: "मराठवाड़ा क्षेत्र में गंभीर सूखे की स्थिति।",
        descriptionMr: "मराठवाडा विभागात तीव्र दुष्काळ परिस्थिती.",
        affectedCrops: ["Soybean", "Cotton", "Tur", "Jowar"],
        recommendedActions: ["Conserve water", "Apply for drought relief", "Consider crop diversification", "Apply for RWBCIS weather insurance"],
        insuranceSuggestion: "RWBCIS",
        isActive: true
      },
      {
        district: "Kolhapur",
        riskType: "flood",
        riskLevel: "high",
        description: "High flood risk due to heavy rainfall. Sugarcane and rice crops may be affected.",
        descriptionHi: "भारी वर्षा से बाढ़ का खतरा अधिक। गन्ना और चावल की फसल प्रभावित हो सकती है।",
        descriptionMr: "जास्त पावसामुळे पुराचा धोका अधिक. ऊस आणि भात पिकांवर परिणाम होऊ शकतो.",
        affectedCrops: ["Sugarcane", "Rice"],
        recommendedActions: ["Move produce to higher ground", "Apply for flood relief", "Ensure PMFBY coverage"],
        insuranceSuggestion: "PMFBY_KHARIF",
        isActive: true
      }
    ];

    for (const alert of weatherAlerts) {
      await prisma.weatherRiskAlert.create({ data: alert });
      console.log(`   ✅ ${alert.district} - ${alert.riskType}`);
    }

    console.log('\n✅ Seed process completed successfully!');
    console.log(`   📋 ${governmentSchemes.length} Government Schemes`);
    console.log(`   🛡️  ${insuranceProducts.length} Insurance Products`);
    console.log(`   ⛈️  ${weatherAlerts.length} Weather Risk Alerts`);

  } catch (error) {
    console.error('❌ Seed error:', error);
  } finally {
    await prisma.$disconnect();
  }
}

seedData();
